PoetExchange/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
	url(r'^login/$', 'users.views.loginRequest'),
	url(r'^logout/$', 'users.views.logoutRequest'),
    url(r'^$', include('objects.urls')),
	url(r'^academics/', include('academics.urls')),
    url(r'^admin/', include(admin.site.urls)),
	url(r'^user/', include('users.urls')),
	url(r'^(?P<user_id>\d+)/$', 'users.views.profile'),
)

users/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin

urlpatterns = patterns( 'users.views',
	url(r'^register/$', 'initRegistration'),
	url(r'^register/(?P<user_slug>[a-z0-9]{2,8})/$', 'mainRegistration'),
)

academics/models.py
#####################
# MODEL DEPENDENCIES
#####################
# ------------------
# DEPENDS ON: 'objects' app
# ------------------
# AcademicClassProfile
# ------------------
# DEPENDS ON: 'users' app
# -----------------
# Book


from django.db import models
from django.core.validators import MaxLengthValidator
from django.template.defaultfilters import slugify

class Book(models.Model) :
	book_seller			= models.ForeignKey('users.SiteUser')
	book_title			= models.CharField(max_length=250)
	book_author			= models.CharField(max_length=250)
	book_class			= models.ForeignKey('AcademicClass')
	book_dept			= models.ForeignKey(
											'AcademicDepartment',
											null=True, 
											editable=False,
										)
	book_price			= models.IntegerField(max_length=3)
	book_condition		= models.CharField(
											max_length=2,
											choices=(
												('BN', 'Brand New'),
												('EX', 'Excellent'),
												('GD', 'Good'),
												('FR', 'Fair'),
												('WT', 'Weathered'),
												('BD', 'Bad'),
												),
										)
	additional_comments	= models.TextField(
											validators=[MaxLengthValidator(500)],
											blank=True, null=True,
											)
	entry_date			= models.DateTimeField(auto_now=True,)
	user_class_key		= models.IntegerField(editable=False,)
	book_slug			= models.SlugField(editable=False, null=True)
	def __unicode__(self) :
		return self.book_title
	def save(self,*args,**kwargs) :
		self.user_class_key = self.book_seller.pk + self.book_class.pk
		self.book_dept = self.book_class.class_dept
		super(Book, self).save(*args, **kwargs)
		self.book_slug = self.pk
		super(Book, self).save(*args, **kwargs)

class AcademicClass(models.Model) :
	class_dept			= models.ForeignKey('AcademicDepartment')
	class_number		= models.IntegerField(max_length=3)
	class_name			= models.CharField(
										max_length=100,
										blank=True, null=True,
									)
	class_professor		= models.ForeignKey(
										'Professor',
										blank=True, null=True,
									)
	last_updated		= models.DateTimeField(auto_now=True)
	unique_key			= models.IntegerField(
										editable=False,
										unique=True,
									)
	ac_slug				= models.SlugField(editable=False)
	def __unicode__(self) :
		return self.class_dept.dept_abrv + ' ' + str(self.class_number)
	def save(self, *args, **kwargs) :
		if not self.id :
			unslugged = "%s %d" % (self.class_dept.dept_abrv, self.class_number)
			self.ac_slug = slugify(unslugged)
		self.unique_key = self.class_dept.pk + self.class_number
		super(AcademicClass, self).save(*args, **kwargs)
	
class AcademicDepartment(models.Model) :
	dept_name			= models.CharField(
											max_length=250,
											unique=True,
										)
	dept_abrv			= models.CharField(
											max_length=4,
											unique=True,
										)
	dept_slug			= models.SlugField(editable=False)
	def __unicode__(self) :
		return self.dept_abrv
	def save(self, *args, **kwargs) :
		dept_slug = slugify(self.dept_abrv)
		super(AcademicDepartment, self).save(*args, **kwargs)

class Professor(models.Model) :
	first_name			= models.CharField(
											max_length=50,
											blank=True, null=True,
											)
	last_name			= models.CharField(max_length=80)
	department			= models.ForeignKey('AcademicDepartment')
	unique_key			= models.CharField(
											max_length=100,
											editable=False,
											unique=True,
										)
	def __unicode__(self) :
		return self.last_name
	def save(self, *args, **kwargs) :
		self.unique_key = self.last_name + self.department.dept_abrv
		super(Professor, self).save(*args, **kwargs)

class AcademicClassProfile(models.Model) :
	ac_class			= models.ForeignKey('AcademicClass')
	semester			= models.ForeignKey('objects.Semester')
	meeting_days		= models.ManyToManyField(
											'objects.WeekDay',
											blank=True, null=True,
										)
	meeting_time		= models.TimeField(blank=True, null=True)
	meeting_room		= models.ForeignKey(
											'objects.CampusRoom',
											blank=True, null=True,
										)
	unique_key			= models.IntegerField(
											editable=False,
											unique=True,
										)
	def __unicode__(self) :
		value = "%s %s" % (self.ac_class, self.semester)
		return value
	def save(self, *args, **kwargs) :
			self.unique_key = self.ac_class.pk + self.semester.pk
			super(AcademicClassProfile, self).save(*args, **kwargs)
		
# For use during testing/debugging
DEPTCHOICES = (
	('ANTH', 'ANTH'),
	('ART', 'ART'),
	('BIOL', 'BIOL'),
	('BSAD', 'BSAD'),
	('CHDV', 'CHDV'),
	('CHEM', 'CHEM'),
	('CHIN', 'CHIN'),
	('COSC', 'COSC'),
	('ECON', 'ECON'),
	('EDUC', 'EDUC'),
	('ENGL', 'ENGL'),
	('ENST', 'ENST'),
	('ENVS', 'ENVS'),
	('FILM', 'FILM'),
	('FREN', 'FREN'),
	('GCS', 'GCS'),
	('GWS', 'GWS'),
	('HIST', 'HIST'),
	('INTD', 'INTD'),
	('JAPN', 'JAPN'),
	('KNS', 'KNS'),
	('MATH', 'MATH'),
	('MUS', 'MUS'),
	('PHIL', 'PHIL'),
	('PHYS', 'PHYS'),
	('PSYC', 'PSYC'),
	('REL', 'REL'),
	('SOC', 'SOC'),
	('SOWK', 'SOWK'),
	('SPAN', 'SPAN'),
	('THEA', 'THEA'),
	('WSP', 'WSP'),
)

PoetExchange/templates/production/base.html
<!DOCTYPE Html PUBLIC>
<html lang='en'>
<head>
	<title>Poet Exchange</title>
	<link rel="stylesheet" href="/static/css/style-default.css" type="text/css" media="screen" />
	{% if uagent.opera %}
	<link rel="stylesheet" href="/static/css/style-default_opera.css" type="text/css" media="screen" />
	{% endif %}
	<link rel="shortcut icon" href="7.gif"><link rel="shortcut icon" href="7.gif">
	{% block headext %}{% endblock headext %}
</head>
<body>
<div id="page-container">
	<div id="header">
		<div id="title-container">
			<h1 id="PoetExchange">PoetExchange</h1>
			<h4 id="tagLine">By the Poet, for the Poet</h4>
		</div><!--title-container-->
		{% block login %}
		<div id="login">
			{% if user.is_authenticated %}
			<span>Welcome, {{ user.username }}!</span><br />
			<a href="{% url users.views.logoutRequest %}">Logout</a>
			{% else %}
			<form method="post" action="/login/">
			{% csrf_token %}
				<input type="text" placeholder="Username" size="8" name="uname"><br>
				<input type="password" placeholder="Password" size="8" name="passwd"><br>
				<input type="submit" name="submit" value="login" id="login-button"><br />
				<a href="{% url users.views.initRegistration %}">Register</a>
			</form>
			{% endif %}
		</div><!--login-->
		{% endblock login %}
	</div><!--header-->
	<div id="{% block navId %}navigation{% endblock navId %}">
		{% block navigation %}
		 &nbsp; <a href='{% url objects.views.index %}'>Home</a> &nbsp; {% block dept_nav %}{% endblock %}
		{% endblock navigation%}
	</div><!--navigation-->
	<div id="{% block contentId %}content-main{% endblock contentId %}">
		{% block content %}
			<br><br><span class="gold">Main content box</span>
		{% endblock content %}
		</div><!--content-main-->
	<div id="widget-container">
		{% block widget1 %}
		<div class="widget-box">
			<br><br><span class="gold">Widget box 1</span>
		</div><!--widget-box-->
		{% endblock widget1 %}
		{% block widget2 %}
		<div class="widget-box"><br><br>
			
			<span class="gold">Widget box 2</span>
		</div><!--widget-box-->
		{% endblock widget2 %}
		{% block widget3 %}
		<div class="widget-box">
			<br><br><span class="gold">Widget box 3</span>
		</div><!--widget-box-->
		{% endblock widget3 %}
	</div><!--widget-container-->
</div><!--page-container-->
<div id='footer'>
	{% block footer %}
	{% endblock footer %}
</div><!--footer-->
</body>
</html>

PoetExchange/templates/production/base_bookDetail.html
{% extends 'production/base_classDetail.html' %}

{% block book_nav %}\ &nbsp; <a href='{% url academics.views.bookDetail book.book_dept book.book_class book.book_slug %}'>{{ book.book_title }}</a>{% endblock book_nav %}

{% block contentId %}content-main{% endblock %}
{% block content %}
<h2 id='bookTitle' class='heading-skin1 heading-font'>{{ book.book_title }}</h2>
<div id='bookSellerInfo' class='full-right block-skin2 heading-font'>
	{{ book.book_seller.user.first_name }} {{ book.book_seller.user.last_name }}<br />
	<a href='mailto:{{ book.book_sellser.user.email }}'>
		{{ book.book_seller.user.email }}
	</a><br />
	{% if book.book_seller.residence %}
		{{ book.book_seller.residence.area }}<br />
	{% endif %}
</div><!--bookSellerInfo-->
<div id='bookInfo' class='full-left block-skin2 heading-font'>
	{{ book.get_book_condition_display }}<br />
	${{ book.book_price }}
</div><!--bookInfo-->
<div id='book-description' class='block-skin2 body-font'>
	{{ book.additional_comments }}
</div><!--book-description-->
{% endblock content %}

PoetExchange/templates/production/base_classDetail.html
{% extends 'production/base_deptDetail.html' %}
{% block headext_deptDetailChild %}
<link rel='stylesheet' type='text/css' href='/static/css/style-classDetail.css'>
{% block headext_classDetailChild %}{% endblock %}
{% endblock headext_deptDetailChild %}

{% block class_nav %}
\ &nbsp; <a href='{% url academics.views.classDetail class.class_dept.dept_abrv class.ac_slug %}'>{{ class.class_number }}</a> &nbsp; {% block book_nav %}{% endblock book_nav %}
{%endblock class_nav %}

{% block content %}
<div id='classDetail-container'>
<div id='class-header' class='header-skin1 heading-font'>
	<h2>{{ class.class_dept.dept_name }} {{ class.class_number }}{% if class.class_name %}: {{ class.class_name }}{% endif %}</h2>
	<div id='subheadings'>
		{% if class.class_professor %}
		{{ class.class_professor }}
		{% else %}
		No professor on record
		{% endif %}
	</div><!--subheadings-->
</div><!--class-header-->

<div id='classBooks-block' class='block-skin1 body-font'>
	<h4 class="heading-font block-heading1">Books available for {{ class.class_dept.dept_abrv }} {{ class.class_number }}</h4>
	{% for book in books %}
	<div class="book-entry">
		<span class='bold'>Title</span> <a href='{% url academics.views.bookDetail book.book_dept.dept_abrv book.book_class.ac_slug book.book_slug %}'>{{ book.book_title }}</a><br />
		<span class='bold'>Price</span> ${{ book.book_price }}<br />
		<span class='bold'>Condition</span> {{ book.book_condition }}<br />
		<span class='bold'>Seller</span> <a href="/{{book.book_seller.user.id}}/">{{ book.book_seller.user.username }}</a><br />
		{% if book.book_seller.residence %}
		<span class='bold'>Location</span> {{ book.book_seller.residence }}<br />
		{% endif %}
	</div><!--book-entry-->
	{% endfor %}
</div><!--classBooks-block-->
<div id='other-dept-courses' class='block-skin1 body-font'>
	<h4 class='heading-font block-heading1'>Other courses in {{ class.class_dept.dept_name }} department</h4>
	<ul>
		{% for course in dept_courses %}
		<li><span class='bold'><a href='{% url academics.views.classDetail course.class_dept.dept_abrv course.ac_slug %}'>{{ course.class_dept.dept_abrv }}.{{ course.class_number }}</a></span> {{ course.class_name }}</li>
		{% endfor %}
	</ul>
</div><!--other-dept-courses-->

<div id='other-prof-courses' class='block-skin1 body-font'>
	{% if class.class_professor %}
	<h4 class='heading-font block-heading1'>Other courses by {% if class.class_professor.first_name %}{{ class.class_professor.first_name }} {% endif %}{{ class.class_professor.last_name }}</h4>
	<ul>
		{% for course in prof_courses %}
		<li><span class='bold'><a href='{% url academics.views.classDetail course.class_dept.dept_abrv course.ac_slug %}'>{{ course.class_dept.dept_abrv }}.{{ course.class_number }}</a></span> {{ course.class_name }}</li>
		{% endfor %}
	</ul>
	{% else %}
	<h4 class='heading-font'>No professor on record for {{ class.class_dept.dept_abrv }} {{ class.class_number }}</h4>
	{% endif %}
</div><!--other-prof-courses-->
</div><!--classDetail-container-->
{% endblock content %}

PoetExchange/templates/production/base_deptDetail.html
{% extends 'production/base_index.html' %}

{% block headext_indexChild %}
<link rel="stylesheet" type="text/css" href="/static/css/style-deptDetail.css" />
{% block headext_deptDetailChild %}{% endblock %}
{% endblock headext_indexChild %}

{% block dept_nav %}\ &nbsp; <a href='{% url academics.views.deptDetail dept.dept_abrv %}'>{{ dept.dept_abrv }}</a> &nbsp; {% block class_nav %}{% endblock %}{% endblock dept_nav %}
{% block contentId %}content-none{% endblock contentId %}
{% block content %}
<div id='dept-container'>
	<h2 id='title' class='header-skin1 heading-font'>{{ dept.dept_name }}</h2>
	<div id="class-block" class='block-skin1 body-font'>
		<ul id="course-list">
			{% for course in classes %}
			<li class="course-item">
			<a href='{% url academics.views.classDetail dept.dept_abrv course.ac_slug %}'><span class="bold">{{ course.class_dept.dept_abrv }}.{{ course.class_number }}</span>&nbsp;&nbsp;
					<span class="item-title">{{ course.class_name }}</span></a>
			</li>
			{% endfor %}
		</ul>
	</div><!--class-block-->
	<div id="faculty-block" class='block-skin1 body-font'>
		<ul id="faculty-list">
			{% for prof in dept.professor_set.all %}
			<li>
				{{ prof.last_name }}
				{% if prof.first_name %}, 
				{{ prof.first_name }}
				{% endif %}
			</li>
			{% endfor %}
		</ul>
	</div><!--faculty-block-->
	<div id='deptBooks-block' class='block-skin1 body-font'>
		{% for book in books %}
		<div class='book-entry'>
			<span class="bold"><a href='{% url academics.views.classDetail dept.dept_abrv book.book_class.ac_slug %}'>{{ book.book_class.class_dept }}.{{ book.book_class.class_number }}</a></span> <span class="item-title"><a href='{% url academics.views.bookDetail dept.dept_abrv book.book_class.ac_slug book.book_slug %}'>{{ book.book_title }}</a></span><br />
			{{ book.seller.username }}
		</div><!--books-entry-->
		{% endfor %}
	</div><!--books-block-->
</div><!--dept-container-->
{% endblock content %}

{% block widget1 %}{% endblock widget1 %}
{% block widget2 %}{% endblock widget2 %}
{% block widget3 %}{% endblock widget3 %}

PoetExchange/templates/production/base_index.html
{% extends 'production/base.html' %}
{% load filter_extras %}

{% block headext %}
<link rel="stylesheet" type="text/css" href="/static/css/style-index.css" />
{% block headext_indexChild %}{% endblock %}
{% endblock headext %}
		
{% block content %}
<div id="dept-container">
		{% for dept in acDepts %}
		<div class="dept-block">
			<div class="block-head"><a href="{% url academics.views.deptDetail dept.dept_abrv %}">{{ dept.dept_abrv }}</a></div><!--block-head-->
				{% for book in  books|lookup:dept.dept_abrv %}
				<div class="block-book"><a href='{% url academics.views.bookDetail dept.dept_abrv book.book_class.ac_slug book.book_slug %}'>{{ book }}</a></div><!--block-book-->
				<div class="hrule-white"></div><!--hrule-->
				{% endfor %}
		</div><!--dept-block-->
		{% endfor %}
	</div><!--dept-container-->
{% endblock content %}
<div id="widget-container">
{% block widget1 %}
<div class="widget-box">
	<span class="heading-font">Latest book postings!</span>
</div><!--widget-box-->
{% endblock widget1 %}

{% block widget2 %}
<div class="widget-box">
	<span class="heading-font">Site news listings!</span>
</div><!--widget-box-->
{% endblock widget2 %}

{% block widget3 %}
<div class="widget-box">
	<span class="heading-font">Campus news!</span>
</div><!--widget-box-->
{% endblock widget3 %}
</div><!--widget-container-->

PoetExchange/templates/production/base_profile.html
{% extends 'production/base.html' %}

{% block content %}
<h1>Books this user is selling</h1>
<u1>
{% for a in allBooks %}
	<li> {{a.book_class}}: {{a}} </li>
{% endfor %}
</u1>
{% endblock content %}